In [5]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv


# Assignment Details
1. Dataset Exploration and Preprocessing                                                                             20%)
•	Download Titanic Dataset and Iris Dataset from Kaggle.
•	Perform exploratory data analysis (EDA):
o	Summarize the dataset (e.g., data types, missing values, unique classes, and descriptive statistics).
•	Preprocess the dataset:
o	Handle missing data if any.
o	Encode categorical variables using suitable methods (e.g., one-hot or label encoding if required).
o	Normalize / Standardize or scale features if required.
________________________________________
2. Model Implementation                                                                                                                    (20%)
•	Train and Evaluate Models:
o	Implement the following classifiers:
	Support Vector Machine (SVM)
	Decision Tree
	Random Forest
	XGBoost
o	Split the data into training and testing sets.
o	Use cross-validation to fine-tune hyperparameters for each classifier.
•	Hyperparameter Tuning:
o	Experiment with different hyperparameters for each model. Examples:
	SVM: Kernel types (linear, poly, RBF).
	Decision Tree: Max depth, criterion (gini vs entropy).
	Random Forest: Number of estimators, max depth.
	XGBoost: Learning rate, max depth, n_estimators.
________________________________________
3. Model Evaluation and Comparison                                                                                               (20%)
•	Evaluate each model's performance using:
o	Accuracy
o	Precision, Recall, and F1-score
•	Generate confusion matrices for each classifier.
•	Compare model performance and discuss their strengths and weaknesses for the chosen dataset.
________________________________________
4. Reporting and Visualization                                                                                                           (20%)
•	Create visualizations to compare the models, such as:
o	Bar plots for evaluation metrics (e.g., accuracy, F1-score).
•	Summarize the findings in a report:
o	Which model performed best and why?
o	How does the choice of hyperparameters impact performance?




Good Luck 🙂


In [6]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns 

# Loading Dataset


In [7]:
train = pd.read_csv("/kaggle/input/titanic/train.csv")
train.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [8]:
test = pd.read_csv("/kaggle/input/titanic/test.csv")
test.head()

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

# Data Preprocessing 

In [9]:
train.shape, test.shape

((891, 12), (418, 11))

In [10]:
df = pd.concat([train, test])

In [11]:
df

/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1458: RuntimeWarning: invalid value encountered in greater
  has_large_values = (abs_vals > 1e6).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in less
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()
/usr/local/lib/python3.11/dist-packages/pandas/io/formats/format.py:1459: RuntimeWarning: invalid value encountered in greater
  has_small_values = ((abs_vals < 10 ** (-self.digits)) & (abs_vals > 0)).any()


PassengerId  Survived  Pclass  \
0              1       0.0       3   
1              2       1.0       1   
2              3       1.0       3   
3              4       1.0       1   
4              5       0.0       3   
..           ...       ...     ...   
413         1305       NaN       3   
414         1306       NaN       1   
415         1307       NaN       3   
416         1308       NaN       3   
417         1309       NaN       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
413                                 Spector, Mr. Woolf    male   NaN      0   
414                       Oliva y Ocana, Dona. Fermina  female  39.0      0   
415                       Saether, Mr. Simon Sivertsen    male  38.5      0   
416                                Ware, Mr. Frederick    male   NaN      0   
417                           Peter, Master. Michael J    male   NaN      1   

     Parch              Ticket      Fare Cabin Embarked  
0        0           A/5 21171    7.2500   NaN        S  
1        0            PC 17599   71.2833   C85        C  
2        0    STON/O2. 3101282    7.9250   NaN        S  
3        0              113803   53.1000  C123        S  
4        0              373450    8.0500   NaN        S  
..     ...                 ...       ...   ...      ...  
413      0           A.5. 3236    8.0500   NaN        S  
414      0            PC 17758  108.9000  C105        C  
415      0  SOTON/O.Q. 3101262    7.2500   NaN        S  
416      0              359309    8.0500   NaN        S  
417      1                2668   22.3583   NaN        C  

[1309 rows x 12 columns]

In [12]:
df['Survived'].unique()

array([ 0.,  1., nan])

In [13]:
df['Survived'].skew()

0.4785234382949897

In [14]:
df['Survived'] = df['Survived'].fillna(df['Survived'].mode()[0])

In [15]:
df.shape

(1309, 12)

In [16]:
df.isnull().sum()

PassengerId       0
Survived          0
Pclass            0
Name              0
Sex               0
Age             263
SibSp             0
Parch             0
Ticket            0
Fare              1
Cabin          1014
Embarked          2
dtype: int64

In [17]:
df = df.drop('Name', axis=1)
df = df.drop('Cabin', axis=1)
df = df.drop('Ticket', axis=1)

In [18]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex', 'Age', 'SibSp', 'Parch',
       'Fare', 'Embarked'],
      dtype='object')

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1309 entries, 0 to 417
Data columns (total 9 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  1309 non-null   int64  
 1   Survived     1309 non-null   float64
 2   Pclass       1309 non-null   int64  
 3   Sex          1309 non-null   object 
 4   Age          1046 non-null   float64
 5   SibSp        1309 non-null   int64  
 6   Parch        1309 non-null   int64  
 7   Fare         1308 non-null   float64
 8   Embarked     1307 non-null   object 
dtypes: float64(3), int64(4), object(2)
memory usage: 102.3+ KB


In [20]:
df.dtypes

PassengerId      int64
Survived       float64
Pclass           int64
Sex             object
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked        object
dtype: object

In [21]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            263
SibSp            0
Parch            0
Fare             1
Embarked         2
dtype: int64

In [22]:
df.dtypes

PassengerId      int64
Survived       float64
Pclass           int64
Sex             object
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked        object
dtype: object

In [23]:
# Select categorical columns
categorical_cols = df.select_dtypes(include='object').columns

# Select Numerical columns
num_cols = df.select_dtypes(include='int64').columns


In [24]:
categorical_cols

Index(['Sex', 'Embarked'], dtype='object')

In [25]:
num_cols

Index(['PassengerId', 'Pclass', 'SibSp', 'Parch'], dtype='object')

In [26]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Sex              0
Age            263
SibSp            0
Parch            0
Fare             1
Embarked         2
dtype: int64

In [27]:
import pandas as pd
from scipy.stats import skew

# Separate column types
categorical_cols = df.select_dtypes(include='object').columns
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Fill missing values in categorical columns with mode
for col in categorical_cols:
    if df[col].isnull().any():
        mode_value = df[col].mode()[0]
        df[col].fillna(mode_value, inplace=True)

# Fill missing values in numerical columns
for col in numerical_cols:
    if df[col].isnull().any():
        col_skew = skew(df[col].dropna())  # avoid skewing from NaNs
        if abs(col_skew) < 0.5:
            df[col].fillna(df[col].mean(), inplace=True)
        else:
            df[col].fillna(df[col].median(), inplace=True)
            

/tmp/ipykernel_35/1199688877.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(mode_value, inplace=True)
/tmp/ipykernel_35/1199688877.py:19: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.

In [28]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64

In [29]:
df['Survived'].unique()

array([0., 1.])

In [30]:
import category_encoders as ce


# Initialize encoder
# use_cat_names=True makes the column names meaningful (color_red, color_blue, etc.).
encoder = ce.OneHotEncoder(cols=categorical_cols, use_cat_names=True)

# Fit and transform
df_encoded = encoder.fit_transform(df)


In [31]:
df_encoded.head()

PassengerId  Survived  Pclass  Sex_male  Sex_female   Age  SibSp  Parch  \
0            1       0.0       3         1           0  22.0      1      0   
1            2       1.0       1         0           1  38.0      1      0   
2            3       1.0       3         0           1  26.0      0      0   
3            4       1.0       1         0           1  35.0      1      0   
4            5       0.0       3         1           0  35.0      0      0   

      Fare  Embarked_S  Embarked_C  Embarked_Q  
0   7.2500           1           0           0  
1  71.2833           0           1           0  
2   7.9250           1           0           0  
3  53.1000           1           0           0  
4   8.0500           1           0           0

In [32]:
df_encoded.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Sex_male', 'Sex_female', 'Age',
       'SibSp', 'Parch', 'Fare', 'Embarked_S', 'Embarked_C', 'Embarked_Q'],
      dtype='object')

In [33]:
df_encoded["Survived"].tail(10)

408    0.0
409    0.0
410    0.0
411    0.0
412    0.0
413    0.0
414    0.0
415    0.0
416    0.0
417    0.0
Name: Survived, dtype: float64

# Splitting Data

In [34]:
x = df_encoded.drop("Survived", axis=1)
y = df_encoded["Survived"]

In [35]:
x.shape, y.shape

((1309, 11), (1309,))

In [36]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

x = scaler.fit_transform(x)

In [37]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [38]:
x_train.shape, x_test.shape

((1047, 11), (262, 11))

# Support Vector Machine (SVM)

In [39]:
from sklearn.svm import SVC

## Kernal Type: Linear

In [40]:
svc = SVC(kernel='linear', random_state=42)

svc.fit(x_train, y_train)

SVC(kernel='linear', random_state=42)

In [41]:
y_train_pred = svc.predict(x_train)
y_train_pred

array([0., 0., 1., ..., 0., 0., 0.])

In [42]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, classification_report
cm = confusion_matrix(y_train,y_train_pred)
acc_s= accuracy_score(y_train,y_train_pred)
f1_s = f1_score(y_train,y_train_pred)
cr = classification_report(y_train, y_train_pred)

print("Results on Training Dataset")
print()
print("Accuracy Score: ",acc_s)
print("F1 Score: ",f1_s)
print()
print(cm)
print()
print(cr)

Results on Training Dataset

Accuracy Score:  0.8433619866284623
F1 Score:  0.651063829787234

[[730  48]
 [116 153]]

              precision    recall  f1-score   support

         0.0       0.86      0.94      0.90       778
         1.0       0.76      0.57      0.65       269

    accuracy                           0.84      1047
   macro avg       0.81      0.75      0.78      1047
weighted avg       0.84      0.84      0.84      1047



In [43]:
y_pred = svc.predict(x_test)
y_pred

array([0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 1.

In [44]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, classification_report
cm = confusion_matrix(y_test,y_pred)
acc_s= accuracy_score(y_test,y_pred)
f1_s = f1_score(y_test,y_pred)
cr = classification_report(y_test, y_pred)

print("Results on Testing Dataset")
print()
print("Accuracy Score: ",acc_s)
print("F1 Score: ",f1_s)
print()
print(cm)
print()
print(cr)

Results on Testing Dataset

Accuracy Score:  0.8587786259541985
F1 Score:  0.7086614173228347

[[180   9]
 [ 28  45]]

              precision    recall  f1-score   support

         0.0       0.87      0.95      0.91       189
         1.0       0.83      0.62      0.71        73

    accuracy                           0.86       262
   macro avg       0.85      0.78      0.81       262
weighted avg       0.86      0.86      0.85       262



## Kernal Type: Poly

In [45]:
svc = SVC(kernel='poly', random_state=42)

svc.fit(x_train, y_train)

SVC(kernel='poly', random_state=42)

In [46]:
y_test_pred = svc.predict(x_train)
y_test_pred

array([0., 0., 1., ..., 0., 0., 0.])

In [47]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, classification_report
cm = confusion_matrix(y_train,y_test_pred)
acc_s= accuracy_score(y_train,y_test_pred)
f1_s = f1_score(y_train,y_test_pred)
cr = classification_report(y_train, y_test_pred)

print("Results on Training Dataset")
print()
print("Accuracy Score: ",acc_s)
print("F1 Score: ",f1_s)
print()
print(cm)
print()
print(cr)

Results on Training Dataset

Accuracy Score:  0.8806112702960841
F1 Score:  0.7191011235955057

[[762  16]
 [109 160]]

              precision    recall  f1-score   support

         0.0       0.87      0.98      0.92       778
         1.0       0.91      0.59      0.72       269

    accuracy                           0.88      1047
   macro avg       0.89      0.79      0.82      1047
weighted avg       0.88      0.88      0.87      1047



In [48]:
y_pred = svc.predict(x_test)
y_pred

array([0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 0., 0., 1.

In [49]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, classification_report
cm = confusion_matrix(y_test,y_pred)
acc_s= accuracy_score(y_test,y_pred)
f1_s = f1_score(y_test,y_pred)
cr = classification_report(y_test, y_pred)

print("Results on Testing Dataset")
print()
print("Accuracy Score: ",acc_s)
print("F1 Score: ",f1_s)
print()
print(cm)
print()
print(cr)

Results on Testing Dataset

Accuracy Score:  0.851145038167939
F1 Score:  0.6829268292682927

[[181   8]
 [ 31  42]]

              precision    recall  f1-score   support

         0.0       0.85      0.96      0.90       189
         1.0       0.84      0.58      0.68        73

    accuracy                           0.85       262
   macro avg       0.85      0.77      0.79       262
weighted avg       0.85      0.85      0.84       262



## Kernal Type: RBF

In [50]:
svc = SVC(kernel='rbf', random_state=42)

svc.fit(x_train, y_train)

SVC(random_state=42)

In [51]:
y_train_pred = svc.predict(x_train)
y_train_pred

array([1., 0., 1., ..., 0., 0., 0.])

In [52]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, classification_report
cm = confusion_matrix(y_train,y_train_pred)
acc_s= accuracy_score(y_train,y_train_pred)
f1_s = f1_score(y_train,y_train_pred)
cr = classification_report(y_train, y_train_pred)

print("Results on Training Dataset")
print()
print("Accuracy Score: ",acc_s)
print("F1 Score: ",f1_s)
print()
print(cm)
print()
print(cr)

Results on Training Dataset

Accuracy Score:  0.8758357211079274
F1 Score:  0.7257383966244725

[[745  33]
 [ 97 172]]

              precision    recall  f1-score   support

         0.0       0.88      0.96      0.92       778
         1.0       0.84      0.64      0.73       269

    accuracy                           0.88      1047
   macro avg       0.86      0.80      0.82      1047
weighted avg       0.87      0.88      0.87      1047



In [53]:
y_pred = svc.predict(x_test)
y_pred

array([0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 1., 0., 0., 0., 0., 1., 1., 1., 0., 1., 1.,
       0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0.,
       1., 0., 0., 0., 1.

In [54]:
from sklearn.metrics import confusion_matrix, accuracy_score, f1_score, classification_report
cm = confusion_matrix(y_test,y_pred)
acc_s= accuracy_score(y_test,y_pred)
f1_s = f1_score(y_test,y_pred)
cr = classification_report(y_test, y_pred)

print("Results on Testing Dataset")
print()
print("Accuracy Score: ",acc_s)
print("F1 Score: ",f1_s)
print()
print(cm)
print()
print(cr)

Results on Testing Dataset

Accuracy Score:  0.8740458015267175
F1 Score:  0.7441860465116279

[[181   8]
 [ 25  48]]

              precision    recall  f1-score   support

         0.0       0.88      0.96      0.92       189
         1.0       0.86      0.66      0.74        73

    accuracy                           0.87       262
   macro avg       0.87      0.81      0.83       262
weighted avg       0.87      0.87      0.87       262



## cross-validation to fine-tune hyperparameters for Support Vector Classifier

In [55]:
from sklearn.model_selection import GridSearchCV

In [56]:
# Define parameter grid
param_grid = {
    'C': [0.1, 1], # Regularization strength (smaller = more regularization)
    'kernel': ['linear', 'rbf', 'poly'], # 'linear', 'rbf', 'poly', 'sigmoid'
    'gamma': ['scale', 0.1]  # Kernel coefficient for 'rbf', 'poly', and 'sigmoid' kernels 
}

# Initialize GridSearchCV
grid_search = GridSearchCV(SVC(), param_grid, cv=5, scoring='accuracy')

# Fit on training data
grid_search.fit(x_train, y_train)

# Best parameters
print("Best Parameters:", grid_search.best_params_)

# Evaluate on test set
best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_test)
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Best Parameters: {'C': 1, 'gamma': 0.1, 'kernel': 'poly'}

Classification Report:
               precision    recall  f1-score   support

         0.0       0.86      0.96      0.90       189
         1.0       0.84      0.59      0.69        73

    accuracy                           0.85       262
   macro avg       0.85      0.77      0.80       262
weighted avg       0.85      0.85      0.85       262



# Decision Tree

In [57]:
from sklearn.tree import DecisionTreeClassifier

## Criterion: Entropy

In [58]:
dtc = DecisionTreeClassifier(criterion="entropy", splitter="best", max_depth=10)
dtc.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=10)

In [59]:
y_pred = dtc.predict(x_test)
y_pred

array([0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 1., 0.,
       0., 0., 1., 0., 1.

In [60]:
report = classification_report (y_pred, y_test)
print(report)

              precision    recall  f1-score   support

         0.0       0.93      0.89      0.91       197
         1.0       0.70      0.78      0.74        65

    accuracy                           0.86       262
   macro avg       0.81      0.84      0.82       262
weighted avg       0.87      0.86      0.87       262



## Criterion: Gini

In [61]:
dtc = DecisionTreeClassifier(criterion="gini", splitter="best", max_depth=10)
dtc.fit(x_train, y_train)

DecisionTreeClassifier(max_depth=10)

In [62]:
y_pred = dtc.predict(x_test)

report = classification_report (y_pred, y_test)
print(report)

              precision    recall  f1-score   support

         0.0       0.90      0.87      0.88       196
         1.0       0.64      0.71      0.68        66

    accuracy                           0.83       262
   macro avg       0.77      0.79      0.78       262
weighted avg       0.84      0.83      0.83       262



## Hyperparameter Grid for GridSearchCV

In [63]:
from sklearn.model_selection import GridSearchCV

param_grid = {
    'criterion': ['gini', 'entropy'],
    'max_depth': [3, 5, 10, None],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'max_features': ['sqrt', 'log2', None]
}

grid_search = GridSearchCV(DecisionTreeClassifier(random_state=42), param_grid, cv=5, scoring='accuracy', n_jobs=-1)
grid_search.fit(x_train, y_train)

print("Best Parameters:", grid_search.best_params_)


Best Parameters: {'criterion': 'gini', 'max_depth': 5, 'max_features': None, 'min_samples_leaf': 1, 'min_samples_split': 2}


In [64]:
from sklearn.metrics import classification_report

best_model = grid_search.best_estimator_
y_pred = best_model.predict(x_test)
print(classification_report(y_test, y_pred))


              precision    recall  f1-score   support

         0.0       0.89      0.91      0.90       189
         1.0       0.75      0.71      0.73        73

    accuracy                           0.85       262
   macro avg       0.82      0.81      0.82       262
weighted avg       0.85      0.85      0.85       262



# Random Forest

In [65]:
from sklearn.ensemble import RandomForestClassifier


In [66]:
rfc = RandomForestClassifier(n_estimators=100, max_depth=10)
rfc.fit(x_train, y_train)


RandomForestClassifier(max_depth=10)

In [68]:
y_pred = rfc.predict(x_test)
y_pred

array([0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 1., 1., 0., 0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 1.,
       0., 0., 0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 1., 1., 0., 1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 0.,
       0., 0., 1., 0., 0., 0., 1., 1., 0., 0., 0., 0., 1., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 1., 0.,
       1., 0., 1., 0., 1.

In [69]:
report = classification_report (y_pred, y_test)
print(report)

              precision    recall  f1-score   support

         0.0       0.94      0.89      0.92       199
         1.0       0.71      0.83      0.76        63

    accuracy                           0.88       262
   macro avg       0.83      0.86      0.84       262
weighted avg       0.89      0.88      0.88       262



## cross-validation for random forest

In [73]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold

rfc = RandomForestClassifier(n_estimators=100, max_depth=10, random_state=42)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# When class labels are imbalanced, KFold might split them unevenly across folds. StratifiedKFold ensures each fold maintains the same class distribution as the full dataset.
scores = cross_val_score(rfc, x, y, cv=skf, scoring='accuracy')

print("Stratified Cross-Validation Accuracy Scores:", scores)
print("Mean Accuracy:", scores.mean())


Stratified Cross-Validation Accuracy Scores: [0.85496183 0.90839695 0.8778626  0.88549618 0.88122605]
Mean Accuracy: 0.881588722178351


# XGBoost

In [74]:
import xgboost as xgb

In [ ]:
data_matrix = xgb.DMatrix(data=x, label=y)

In [77]:
from xgboost import XGBClassifier

params = {
    'objective': 'binary:logistic',
    'max_depth': 5,
    'reg_alpha': 10,
    'learning_rate' : 1.0,
    'n_estimators': 100
}

model = XGBClassifier(**params)
model.fit(x_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=1.0, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=5, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=100, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [79]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0,
       1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1])

In [82]:
from sklearn.metrics import accuracy_score, f1_score

acs = accuracy_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred, average = 'binary')
cm = confusion_matrix(y_test, y_pred)
print("Accuracy Score: ", acs)
print("F1 Score: ", f1)
print(cm)

Accuracy Score:  0.8664122137404581
F1 Score:  0.7368421052631579
[[178  11]
 [ 24  49]]


## Cross Validation for XGBoost 

In [90]:
import sklearn
sklearn.metrics.get_scorer_names()

['accuracy',
 'adjusted_mutual_info_score',
 'adjusted_rand_score',
 'average_precision',
 'balanced_accuracy',
 'completeness_score',
 'explained_variance',
 'f1',
 'f1_macro',
 'f1_micro',
 'f1_samples',
 'f1_weighted',
 'fowlkes_mallows_score',
 'homogeneity_score',
 'jaccard',
 'jaccard_macro',
 'jaccard_micro',
 'jaccard_samples',
 'jaccard_weighted',
 'matthews_corrcoef',
 'max_error',
 'mutual_info_score',
 'neg_brier_score',
 'neg_log_loss',
 'neg_mean_absolute_error',
 'neg_mean_absolute_percentage_error',
 'neg_mean_gamma_deviance',
 'neg_mean_poisson_deviance',
 'neg_mean_squared_error',
 'neg_mean_squared_log_error',
 'neg_median_absolute_error',
 'neg_negative_likelihood_ratio',
 'neg_root_mean_squared_error',
 'normalized_mutual_info_score',
 'positive_likelihood_ratio',
 'precision',
 'precision_macro',
 'precision_micro',
 'precision_samples',
 'precision_weighted',
 'r2',
 'rand_score',
 'recall',
 'recall_macro',
 'recall_micro',
 'recall_samples',
 'recall_weighted',

In [89]:
from sklearn.model_selection import cross_validate, StratifiedKFold
from xgboost import XGBClassifier

xgb = XGBClassifier(**params)

skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# Use multiple scoring metrics
scoring = ['accuracy', 'precision_macro', 'recall_macro', 'f1_macro']

results = cross_validate(xgb, x, y, cv=skf, scoring=scoring, return_train_score=True)

# Print test scores
for metric in scoring:
    print(f"Mean {metric}: {results[f'test_{metric}'].mean():.4f}")


Mean accuracy: 0.8579
Mean precision_macro: 0.8293
Mean recall_macro: 0.7924
Mean f1_macro: 0.8060
