In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/social-network-ads/Social_Network_Ads (1).csv


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Loading Dataset

In [3]:
df = pd.read_csv("/kaggle/input/social-network-ads/Social_Network_Ads (1).csv")

In [4]:
df

User ID  Gender  Age  EstimatedSalary  Purchased
0    15624510    Male   19            19000          0
1    15810944    Male   35            20000          0
2    15668575  Female   26            43000          0
3    15603246  Female   27            57000          0
4    15804002    Male   19            76000          0
..        ...     ...  ...              ...        ...
395  15691863  Female   46            41000          1
396  15706071    Male   51            23000          1
397  15654296  Female   50            20000          1
398  15755018    Male   36            33000          0
399  15594041  Female   49            36000          1

[400 rows x 5 columns]

In [5]:
df.isnull().sum()

User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [6]:
df["Gender"].unique()

array(['Male', 'Female'], dtype=object)

In [7]:
df = df.join(pd.get_dummies(df["Gender"]))


In [8]:
df

User ID  Gender  Age  EstimatedSalary  Purchased  Female   Male
0    15624510    Male   19            19000          0   False   True
1    15810944    Male   35            20000          0   False   True
2    15668575  Female   26            43000          0    True  False
3    15603246  Female   27            57000          0    True  False
4    15804002    Male   19            76000          0   False   True
..        ...     ...  ...              ...        ...     ...    ...
395  15691863  Female   46            41000          1    True  False
396  15706071    Male   51            23000          1   False   True
397  15654296  Female   50            20000          1    True  False
398  15755018    Male   36            33000          0   False   True
399  15594041  Female   49            36000          1    True  False

[400 rows x 7 columns]

In [9]:
df["Male"] = df["Male"].apply(lambda x: 1 if x == 1 else 0)
df["Female"] = df["Female"].apply(lambda x: 1 if x == 1 else 0)


In [10]:
df

User ID  Gender  Age  EstimatedSalary  Purchased  Female  Male
0    15624510    Male   19            19000          0       0     1
1    15810944    Male   35            20000          0       0     1
2    15668575  Female   26            43000          0       1     0
3    15603246  Female   27            57000          0       1     0
4    15804002    Male   19            76000          0       0     1
..        ...     ...  ...              ...        ...     ...   ...
395  15691863  Female   46            41000          1       1     0
396  15706071    Male   51            23000          1       0     1
397  15654296  Female   50            20000          1       1     0
398  15755018    Male   36            33000          0       0     1
399  15594041  Female   49            36000          1       1     0

[400 rows x 7 columns]

# Splitting Dataset 

In [11]:
x = df.iloc[:,[2,3,5,6]]
y = df.iloc[:, 4]


# Splitting Dataset into Trainnig and Testing

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state = 42)

# Feature Scaling

In [14]:
from sklearn.preprocessing import StandardScaler 

In [15]:
scaler = StandardScaler()

In [16]:
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [17]:
x_train

array([[-1.06675246, -0.38634438,  1.        , -1.        ],
       [ 0.79753468, -1.22993871, -1.        ,  1.        ],
       [ 0.11069205,  1.853544  ,  1.        , -1.        ],
       ...,
       [ 0.50317355,  1.82445454,  1.        , -1.        ],
       [ 0.11069205,  0.19544481, -1.        ,  1.        ],
       [-0.57615058,  0.45724994,  1.        , -1.        ]])

In [18]:
x_test

array([[ 0.79753468, -1.40447546,  1.        , -1.        ],
       [ 2.07309956,  0.51542886,  1.        , -1.        ],
       [-0.96863208, -0.76450736,  1.        , -1.        ],
       [ 0.99377543,  0.74814454,  1.        , -1.        ],
       [-0.87051171, -1.22993871,  1.        , -1.        ],
       [-0.77239133, -0.24089709,  1.        , -1.        ],
       [ 0.89565505,  1.06812859,  1.        , -1.        ],
       [-0.87051171,  0.36998156,  1.        , -1.        ],
       [ 0.20881242,  0.13726589, -1.        ,  1.        ],
       [ 0.40505317, -0.15362871, -1.        ,  1.        ],
       [-0.28178945, -0.15362871,  1.        , -1.        ],
       [ 1.4843773 , -1.05540195,  1.        , -1.        ],
       [-1.45923396, -0.64814952,  1.        , -1.        ],
       [-1.75359508, -1.37538601,  1.        , -1.        ],
       [-0.77239133,  0.4863394 , -1.        ,  1.        ],
       [-0.28178945,  1.09721805, -1.        ,  1.        ],
       [ 1.38625693, -0.

# Fitting SVM to Train the Data

In [20]:
from sklearn.svm import SVC

## Linear Kernal 

In [22]:
classifier = SVC(kernel='linear', random_state=42)
classifier.fit(x_train, y_train)

SVC(kernel='linear', random_state=42)

# Predict on Test Data

In [23]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

# Confusion Matrix

In [26]:
 from sklearn.metrics import confusion_matrix, accuracy_score, f1_score

In [27]:
cm = confusion_matrix(y_pred,y_test)
acc_s= accuracy_score(y_pred,y_test)
f1_s = f1_score(y_pred,y_test)

In [28]:
print(acc_s)
print(f1_s)
print(cm)

0.8625
0.7755102040816326
[[50  9]
 [ 2 19]]


## Sigmoid Kernal

In [36]:
classifier = SVC(kernel='sigmoid', random_state=42)
classifier.fit(x_train, y_train)

SVC(kernel='sigmoid', random_state=42)

In [37]:
y_pred = classifier.predict(x_test)
y_pred

array([0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0,
       0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [38]:
cm = confusion_matrix(y_pred,y_test)
acc_s= accuracy_score(y_pred,y_test)
f1_s = f1_score(y_pred,y_test)
print(acc_s)
print(f1_s)
print(cm)

0.8375
0.7346938775510204
[[49 10]
 [ 3 18]]


## Guassian Radial Basis Funtion(RBF) Kernal

In [39]:
classifier = SVC(kernel='rbf', random_state=42)
classifier.fit(x_train, y_train)

SVC(random_state=42)

In [40]:
y_pred = classifier.predict(x_test)
y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0])

In [41]:
cm = confusion_matrix(y_pred,y_test)
acc_s= accuracy_score(y_pred,y_test)
f1_s = f1_score(y_pred,y_test)
print(acc_s)
print(f1_s)
print(cm)

0.925
0.896551724137931
[[48  2]
 [ 4 26]]


# Multi-Class Classification using SVM
Support Vector Machine (SVM) handles multi-class classification using two main strategies:
1. One-vs-Rest (OvR) (default in scikit-learn)
2. One-vs-One (OvO)




| Feature              | OvR                          | OvO                         |
| -------------------- | ---------------------------- | --------------------------- |
| No. of classifiers   | N                            | N(N-1)/2                    |
| Training time        | Faster                       | Slower                      |
| Accuracy (usually)   | Good                         | Often better                |
| Use case             | Many classes, faster results | Few classes, high precision |
| scikit-learn default | `SVC`: OvO (internally)      | `LinearSVC`: OvR            |


**Rule of Thumb**:
- Few classes + more precision = OvO
- Many classes + speed needed = OvR

In [42]:
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix

# Load a multi-class dataset
iris = datasets.load_iris()
X = iris.data
y = iris.target  # Three classes: 0, 1, 2

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# Train SVM (multi-class by default using One-vs-Rest strategy)
model = SVC(kernel='linear', decision_function_shape='ovr')  # or 'ovo'
model.fit(X_train, y_train)

# Predict
y_pred = model.predict(X_test)

# Evaluate
print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred, target_names=iris.target_names))


[[10  0  0]
 [ 0  8  1]
 [ 0  0 11]]
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        10
  versicolor       1.00      0.89      0.94         9
   virginica       0.92      1.00      0.96        11

    accuracy                           0.97        30
   macro avg       0.97      0.96      0.97        30
weighted avg       0.97      0.97      0.97        30

